---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atproto-pds
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      atproto-pds:
        containers:
          app:
            image:
              repository: ghcr.io/bluesky-social/pds
              tag: 0.4.158
            env:
              PDS_PORT: &port 2583
              PDS_HOSTNAME: at.hayden.moe
              PDS_DATA_DIRECTORY: /pds
              PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
              PDS_BLOB_UPLOAD_LIMIT: 52428800
              PDS_DID_PLC_URL: https://plc.directory
              PDS_BSKY_APP_VIEW_URL: https://api.bsky.app
              PDS_BSKY_APP_VIEW_DID: did:web:api.bsky.app
              PDS_REPORT_SERVICE_URL: https://mod.bsky.app
              PDS_REPORT_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
              PDS_CRAWLERS: https://bsky.network
              PDS_EMAIL_FROM_ADDRESS: pds@tem.hayden.moe
              LOG_ENABLED: true
            envFrom:
              - secretRef:
                  name: atproto-pds-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /xrpc/_health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: atproto-pds
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - at.hayden.moe
          - '*.at.hayden.moe'
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: pds
        globalMounts:
          - path: /pds
