---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storage-bucket-gcp
spec:
  compositeTypeRef:
    apiVersion: infra.hayden.moe/v1alpha1
    kind: StorageBucket

  mode: Pipeline

  pipeline:
    - step: render-bucket
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $xr := .observed.composite.resource -}}
            {{- $spec := $xr.spec -}}
            {{- $name := $xr.metadata.name -}}
            {{- $namespace := $xr.metadata.namespace -}}
            {{- $projectID := "" -}}
            {{- with .extraResources -}}
            {{- $projects := index . "service-project" -}}
            {{- range $project := $projects.items -}}
            {{- $projectID = default "" $project.resource.status.projectId -}}
            {{- end -}}
            {{- end -}}
            ---
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: ExtraResources
            requirements:
              service-project:
                apiVersion: infra.hayden.moe/v1alpha1
                kind: ServiceProject
                matchName: {{ $spec.serviceProjectRef.name | quote }}
                namespace: {{ $namespace | quote }}
            {{ if not $projectID }}
            ---
            apiVersion: infra.hayden.moe/v1alpha1
            kind: StorageBucket
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/ready: "False"
            {{ end }}
            {{ if $projectID }}
            ---
            apiVersion: storage.gcp.m.upbound.io/v1beta1
            kind: Bucket
            metadata:
              name: {{ printf "bkt-phb-%s-%.6s" $xr.metadata.name $xr.metadata.uid | quote }}
              namespace: {{ $namespace | quote }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: bucket
            spec:
              forProvider:
                location: {{ $spec.location | quote }}
                project: {{ $projectID | quote }}
              providerConfigRef:
                kind: ClusterProviderConfig
                name: gcp-storage
            {{ if $spec.interoperability.enabled }}
            ---
            apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
            kind: ServiceAccount
            metadata:
              namespace: {{ $namespace | quote }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: bucket-service-account
                crossplane.io/external-name: {{ printf "sa-phb-%.6s-%.6s-s3" $namespace $name | quote }}
            spec:
              forProvider:
                description: S3 Access interop SA for {{ printf "%s/%s" $namespace $name }}
                project: {{ $projectID | quote }}
              providerConfigRef:
                kind: ClusterProviderConfig
                name: gcp-cloudplatform
            ---
            apiVersion: storage.gcp.m.upbound.io/v1beta1
            kind: BucketIAMMember
            metadata:
              namespace: {{ $namespace | quote }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: bucket-service-account-iam
            spec:
              forProvider:
                bucketSelector:
                  matchControllerRef: true
                member: {{ printf "serviceAccount:sa-phb-%.6s-%.6s-s3@%s.iam.gserviceaccount.com" $namespace $name $projectID | quote }}
                role: {{ $spec.role | quote }}
              providerConfigRef:
                kind: ClusterProviderConfig
                name: gcp-storage
            ---
            apiVersion: storage.gcp.m.upbound.io/v1beta1
            kind: HMACKey
            metadata:
              namespace: {{ $namespace | quote }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: bucket-service-account-hmac-key
            spec:
              forProvider:
                project: {{ $projectID | quote }}
                serviceAccountEmail: {{ printf "sa-phb-%.6s-%.6s-s3@%s.iam.gserviceaccount.com" $namespace $name $projectID | quote }}
                state: ACTIVE
              providerConfigRef:
                kind: ClusterProviderConfig
                name: gcp-storage
              writeConnectionSecretToRef:
                name: {{ printf "%s-s3-hmac" $name }}
            {{- if ne $.observed.resources nil }}
            {{- $hmac := index $.observed.resources "bucket-service-account-hmac-key" }}
            {{- if and $hmac $hmac.connectionDetails }}
            ---
            apiVersion: v1
            kind: Secret
            metadata:
              name: {{ printf "%s-s3" $name | quote }}
              namespace: {{ $namespace | quote }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: bucket-s3-credentials
            type: Opaque
            data:
              AWS_ACCESS_KEY_ID: {{ $hmac.resource.status.atProvider.accessId | b64enc | quote }}
              AWS_SECRET_ACCESS_KEY: {{ index $hmac.connectionDetails "attribute.secret" | quote }}
            {{- end }}
            {{- end }}
            {{ else }}
            ---
            apiVersion: storage.gcp.m.upbound.io/v1beta1
            kind: BucketIAMMember
            metadata:
              namespace: {{ $namespace | quote }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: bucket-k8s-sa-iam-member
            spec:
              forProvider:
                bucketSelector:
                  matchControllerRef: true
                member: {{ printf "principal://iam.googleapis.com/projects/754336396991/locations/global/workloadIdentityPools/kube-talos-phoebe/subject/system:serviceaccount:%s:%s" $namespace $spec.serviceAccount | quote }}
                role: {{ $spec.role | quote }}
              providerConfigRef:
                kind: ClusterProviderConfig
                name: gcp-storage
            {{ end }}
            {{ end }}

    - step: automatically-detect-readiness
      functionRef:
        name: function-auto-ready
