---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openthread
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "iot",
            "namespace": "kube-system",
            "ips": ["192.168.20.23/24", "fd74:f571:d3bd:40:41d7:bb2e:6c90:a8f5/64"],
            "mac": "c6:07:27:af:fb:56"
          }]
      securityContext:
        runAsNonRoot: false # Must be run as root user
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [34]
        sysctls:
          - name: net.ipv6.conf.net1.accept_ra
            value: "2"
          - name: net.ipv6.conf.net1.forwarding
            value: "1"
          - name: net.ipv6.conf.net1.accept_ra_rt_info_max_plen
            value: "64"
          - name: net.ipv6.conf.all.forwarding
            value: "1"

    controllers:
      otbr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/wittdennis/homeassistant-otbr
              tag: 4.2.3@sha256:1b53b0b3488e1ee0929c1b28a231552f81cdb0cbdc4bcd75a91c2711ab6967fc
            env:
              TZ: Europe/London
              BACKBONE_IF: net1
              BAUDRATE: 460800
              FIREWALL: 0
              NAT64: 1
              NETWORK_DEVICE: /dev/ttyACM0
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: 1
              S6_READ_ONLY_ROOT: 1
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 512Mi
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /node/state
                    port: &port 8081
              readiness: *probe
            securityContext:
              privileged: true
              capabilities:
                add: [NET_ADMIN]

    service:
      otbr:
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data

      dev-net-tun:
        type: hostPath
        hostPath: /dev/net/tun
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/net/tun

      dev-tty:
        type: hostPath
        hostPath: /dev/ttyACM0
        hostPathType: CharDevice

      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /run
            subPath: run
