---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: grafana
spec:
  displayname: Grafana
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/grafana.svg
  kanidmRef:
    name: kanidm
    namespace: security
  origin: https://grafana.hayden.moe/
  redirectUrl:
    - https://grafana.hayden.moe/login
    - https://grafana.hayden.moe/login/generic_oauth
  scopeMap:
    - group: grafana_users
      scopes:
        - openid
        - profile
        - email
        - groups

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-users
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  kanidmName: grafana_users
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - hayden

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-editors
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  kanidmName: grafana_editors
  accountPolicy:
    authSessionExpiry: 2678400
  members: []

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-admins
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  kanidmName: grafana_admins
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - hayden
