---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: moneat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: moneat-secret
    template:
      data:
        JWT_SECRET: "{{ .jwtSecret }}"
        DATA_SOURCE_ENCRYPTION_KEY: "{{ .dsEncryptionKey }}"
        WORKFLOWS_CONNECTION_KEK: "{{ .workflowsConnectionKek }}"
        WORKFLOWS_SIGNING_KEY: "{{ .workflowsSigningKey }}"
        WORKFLOWS_TEMPORAL_PAYLOAD_KEY: "{{ .workflowsTemporalPayloadKey }}"
  dataFrom:
    - extract:
        key: app-moneat
