---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: miniflux-secret
    template:
      data:
        CREATE_ADMIN: '1'
        ADMIN_USERNAME: '{{ .username }}'
        ADMIN_PASSWORD: '{{ .password }}'
        OAUTH2_CLIENT_ID: '{{ .clientId }}'
        OAUTH2_CLIENT_SECRET: '{{ .clientSecret }}'
        OAUTH2_USER_CREATION: '1'
        OAUTH2_OIDC_DISCOVERY_ENDPOINT: https://sso.hayden.moe/oauth2/openid/{{ .clientId }}
        OAUTH2_PROVIDER: oidc
        OAUTH2_REDIRECT_URL: https://miniflux.hayden.moe/oauth2/oidc/callback
  dataFrom:
    - extract:
        key: app-miniflux
