---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sso-hayden-moe
spec:
  dnsNames:
    - sso.hayden.moe
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: sso-hayden-moe-tls
  usages:
    - digital signature
