resource "upcloud_managed_object_storage_bucket" "self" {
  name = var.name
  service_uuid = var.storage_uuid
}

resource "upcloud_managed_object_storage_user" "self" {
  username = "os-${var.name}-rw"
  service_uuid = var.storage_uuid
}

resource "upcloud_managed_object_storage_user_access_key" "self" {
  username     = upcloud_managed_object_storage_user.self.username
  service_uuid = var.storage_uuid
  status       = "Active"
}

resource "onepassword_item" "self_token" {
  vault = var.op_vault
  title = try(var.op_title, "${var.name}-uc-os")
  category = "secure_note"
  note_value = "Generated by Terraform"
  tags = ["upcloud", "object-storage", "bucket", "terraform"]

  section {
    label = "uc-os_${var.name}"

    # field {
    #   label = "endpoint"
    #   type = "STRING"
    #   value = "https://${cloudflare_r2_bucket.self.name}.r2.cloudflarestorage.com/${cloudflare_r2_bucket.self.name}"
    # }

    field {
      label = "bucket_name"
      type = "STRING"
      value = "${upcloud_managed_object_storage_bucket.self.name}"
    }

    field {
      label = "access_key_id"
      type = "CONCEALED"
      value = upcloud_managed_object_storage_user_access_key.self.access_key_id
    }

    field {
      label = "secret_access_key"
      type = "CONCEALED"
      value = upcloud_managed_object_storage_user_access_key.self.secret_access_key
    }
  }
}
