---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: haos
  namespace: selfhosted

spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: haos
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "false"

    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4G

        devices:
          disks:
            - name: haos-pvc
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio

          interfaces:
            - name: default
              masquerade: {}

      networks:
        - name: default
          pod: {}

      volumes:
        - name: haos-pvc
          persistentVolumeClaim:
            claimName: haos-pvc

        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              network:
                version: 1
                config:
                  - type: physical
                    name: eth0
                    subnets:
                      - type: dhcp

            userData: |-
              #cloud-config
              users:
                - name: hayden
                  ssh_authorized_keys:
                    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDkhuhfzyg7R+O62XSktHufGmmhy6FNDi/NuPPJt7bI+
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo
                  shell: /bin/bash

  dataVolumeTemplates:
  - metadata:
      name: haos-pvc
    spec:
      storage:
        resources:
          requests:
            storage: 35Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: ceph-block
      source:
        http:
          url: https://github.com/home-assistant/operating-system/releases/download/17.2/haos_generic-x86-64-17.2.img.xz
