---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: netbox
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      registry: ghcr.io
      repository: netbox-community/netbox
      tag: v4.5.9@sha256:5e331fb1575c21838af15c4fd59e700488d6253f0f5cacc4b180e422607fa45f

    allowedHosts:
      - ${APP}.hayden.moe

    email:
      server: smtp-relay
      from: netbox@hayden.moe

    postgresql:
      enabled: false

    externalDatabase:
      host: "${APP}-pg-rw"
      port: 5432
      database: app
      username: app
      existingSecretName: "${APP}-pg-app"
      existingSecretKey: password

    valkey:
      enabled: false
    tasksDatabase:
      host: "${APP}-redis"
    cachingDatabase:
      host: "${APP}-redis"

    persistence:
      existingClaim: "${APP}"

    httpRoute:
      enabled: true
      hostnames: ["${APP}.hayden.moe"]
      parentRefs:
        - name: internal
          namespace: network
          sectionName: https

