---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: netbox
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      registry: ghcr.io
      repository: netbox-community/netbox
      tag: v4.6.0@sha256:bd1f7c2b4ae4ca297e6d56a41ed7b8ae95283a14e5281a2229db72661c3dc9aa

    allowedHosts:
      - ${APP}.hayden.moe

    email:
      server: smtp-relay
      from: netbox@hayden.moe

    postgresql:
      enabled: false

    externalDatabase:
      host: "${APP}-pg-rw"
      port: 5432
      database: app
      username: app
      existingSecretName: "${APP}-pg-app"
      existingSecretKey: password

    valkey:
      enabled: false
    tasksDatabase:
      host: "${APP}-redis"
    cachingDatabase:
      host: "${APP}-redis"

    persistence:
      existingClaim: "${APP}"

    httpRoute:
      enabled: true
      hostnames: ["${APP}.hayden.moe"]
      backendRefs:
        - kind: Service
          name: netbox-anubis
          port: 80
      parentRefs:
        - name: internal
          namespace: network
          sectionName: https
