---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: namespacefolders.infra.hayden.moe
spec:
  scope: Namespaced

  group: infra.hayden.moe

  names:
    kind: NamespaceFolder
    plural: namespacefolders
    singular: namespacefolder

  enforcedCompositionRef:
    name: namespace-folder-gcp

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: {}
