[env]
_.python.venv = { path = "{{ config_root }}/.venv", create = true }
KUBECONFIG = "{{ config_root }}/talos/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{ config_root }}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{ config_root }}/age.key"
TALOSCONFIG = "{{ config_root }}/talos/talosconfig"
TALOS_SCHEMATIC="873759897e719eea74d3139eced7b4fc3b64dc5d3124be3f3ae85751c10d6bcb"
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
KUBERNETES_VERSION="v1.33.1"
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
TALOS_VERSION="v1.10.3"

[tools]
"python" = "3.13"
"pipx:makejinja" = "2.7.2"
"aqua:budimanjojo/talhelper" = "3.0.29"
"aqua:cilium/cilium-cli" = "0.18.4"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.6.1"
"aqua:getsops/sops" = "3.10.2"
"aqua:helm/helm" = "3.18.2"
"aqua:helmfile/helmfile" = "1.1.2"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:siderolabs/talos" = "1.10.3"
"aqua:casey/just" = "1.40.0"
"aqua:mikefarah/yq" = "latest"
