[env]
_.python.venv = { path = "{{ config_root }}/.venv", create = true }
KUBECONFIG = "{{ config_root }}/talos/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{ config_root }}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{ config_root }}/age.key"
TALOSCONFIG = "{{ config_root }}/talos/talosconfig"
TALOS_SCHEMATIC="74bd9e7fe18dd9a6a05f3b7d430bfdd477a7a5dba1423db67d11f27ae79327b7"
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
KUBERNETES_VERSION="v1.33.1"
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
TALOS_VERSION="v1.10.3"

[tools]
"python" = "3.13"
"pipx:makejinja" = "2.8.0"
"aqua:budimanjojo/talhelper" = "3.0.31"
"aqua:cilium/cilium-cli" = "0.18.5"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.6.4"
"aqua:getsops/sops" = "3.10.2"
"aqua:helm/helm" = "3.18.4"
"aqua:helmfile/helmfile" = "1.1.3"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:siderolabs/talos" = "1.10.5"
"aqua:casey/just" = "1.42.3"
"aqua:mikefarah/yq" = "latest"
