---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hayden-moe
spec:
  dnsNames:
    - hayden.moe
    - "*.hayden.moe"
    - "*.at.hayden.moe"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: hayden-moe-tls
  usages:
    - digital signature
