---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ntfy
  namespace: &namespace selfhosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kopiur
    - ../../../../components/kanidm/private
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/selfhosted/ntfy/app
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      OIDC_DISPLAY_NAME: NTFY!
      OIDC_IMAGE_URL: https://picsum.photos/256/256
      OIDC_ORIGIN: https://ntfy.hayden.moe
      OIDC_REDIRECT_URLS: '["https://ntfy.hayden.moe"]'
      OIDC_SECRET_ROTATION_ENABLED: 'false'
      OIDC_SECRET_ROTATION_PERIOD_DAYS: '30'
      OIDC_SECRET_KEY_ALIASES: '{clientId: [key], clientSecret: [clientSec]}'
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
