---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinepods
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  values:
    controllers:
      app:
        initContainers:
          install-ca-certificates:
            image:
              repository: alpine
              tag: 3.22
            command:
              - /bin/sh
              - -ec
              - |
                apk add --no-cache ca-certificates

                cp /tmp/postgres.crt /usr/local/share/ca-certificates/postgres.crt
                cp /tmp/root-ca.crt /usr/local/share/ca-certificates/root-ca.crt

                update-ca-certificates

                cp /etc/ssl/certs/ca-certificates.crt /ca-bundle/ca-certificates.crt

        containers:
          app:
            image:
              repository: madeofpendletonwool/pinepods
              tag: 0.9.0@sha256:ebc258bb0c62cdb69e5fb726b247c885dac19b50d06fed68fa8d37197b88ace4
            env:
              SEARCH_API_URL: https://search.pinepods.online/api/search
              PEOPLE_API_URL: https://people.pinepods.online
              HOSTNAME: 'https://pinepods.hayden.moe'

              DB_TYPE: postgresql
              DB_HOST:
                secretKeyRef:
                  name: pinepods-postgres
                  key: host
              DB_PORT: 5432
              DB_USER:
                secretKeyRef:
                  name: pinepods-postgres
                  key: username
              DB_PASSWORD:
                secretKeyRef:
                  name: pinepods-postgres
                  key: password
              DB_NAME:
                secretKeyRef:
                  name: pinepods-postgres
                  key: database

              VALKEY_HOST: pinepods-redis
              VALKEY_PORT: 6379
              DEBUG_MODE: true

              TZ: Europe/London
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 3Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: app
        ports:
          http:
            port: 8040

    route:
      app:
        hostnames:
          - pinepods.hayden.moe
        parentRefs:
          - name: external
            namespace: network

    persistence:
      postgresClient:
        type: secret
        name: postgres-client
        items:
          - key: ca.crt
            path: postgres.crt
        advancedMounts:
          app:
            install-ca-certificates:
              - path: /tmp/postgres.crt
                subPath: postgres.crt

      rootCa:
        type: secret
        name: root-ca
        items:
          - key: ca.crt
            path: root-ca.crt
        advancedMounts:
          app:
            install-ca-certificates:
              - path: /tmp/root-ca.crt
                subPath: root-ca.crt

      caBundle:
        type: emptyDir
        advancedMounts:
          app:
            install-ca-certificates:
              - path: /ca-bundle
            app:
              - path: /etc/ssl/certs
                readOnly: true

      downloads:
        existingClaim: pinepods
        globalMounts:
          - path: /opt/pinepods/downloads
            subPath: downloads
          - path: /opt/pinepods/backups
            subPath: backups

      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
