---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: "${REDIS_APP:-${APP}-redis}"
spec:
  replicas: 1
  args:
    - "--admin_bind=::"
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - "--default_lua_flags=allow-undeclared-keys"
  labels:
    egress.policy.home.arpa/block-all: "true"
  networkPolicyEnabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: ${REDIS_MEMORY:-512Mi}
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
