---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ${REDIS_APP:-${APP}-redis}
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/components/redis/app
  postBuild:
    substitute:
      APP: *app
      REDIS_CAPACITY: ${REDIS_CAPACITY:-2Gi}
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ${NAMESPACE:-default}
  timeout: 5m
  wait: false
