---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maybe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: maybe-secret
    template:
      data:
        SECRET_KEY_BASE: '{{ .secretKey }}'
        CLOUDFLARE_ACCOUNT_ID: '{{ .cloudflareAccountId }}'
        CLOUDFLARE_ACCESS_KEY_ID: '{{ .cloudflareAccessKeyId }}'
        CLOUDFLARE_SECRET_ACCESS_KEY: '{{ .cloudflareSecretAccessKey }}'
        CLOUDFLARE_BUCKET: '{{ .cloudflareBucket }}'
  dataFrom:
    - extract:
        key: maybe
