---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: "${APP}-kanidm-groups"
  namespace: "${NAMESPACE}"
spec:
  dependsOn:
    - name: kaniop-instance
      namespace: security
  healthChecks:
    - apiVersion: kaniop.rs/v1beta1
      kind: KanidmGroup
      name: ${APP}-users
      namespace: ${NAMESPACE}
    - apiVersion: kaniop.rs/v1beta1
      kind: KanidmGroup
      name: ${APP}-admins
      namespace: ${NAMESPACE}
  interval: 1h
  path: ./kubernetes/components/kanidm/base/groups
  postBuild:
    substitute:
      APP: ${APP}
      emptyArray: "[]"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ${NAMESPACE}
  timeout: 5m
  wait: false

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: "${APP}-kanidm"
  namespace: "${NAMESPACE}"
spec:
  dependsOn:
    - name: kaniop-instance
      namespace: security
  healthChecks:
    - apiVersion: kaniop.rs/v1beta1
      kind: KanidmOAuth2Client
      name: ${APP}
      namespace: ${NAMESPACE}
  interval: 1h
  path: ./kubernetes/components/kanidm/base/client
  postBuild:
    substitute:
      APP: ${APP}
      OIDC_DISPLAY_NAME: ${q:='}${OIDC_DISPLAY_NAME}${q:='}
      OIDC_IMAGE_URL: ${q:='}${OIDC_IMAGE_URL}${q:='}
      OIDC_ORIGIN: ${q:='}${OIDC_ORIGIN}${q:='}
      OIDC_REDIRECT_URLS: ${q:='}${OIDC_REDIRECT_URLS}${q:='}
      OIDC_SECRET_ROTATION_ENABLED: ${q:='}${OIDC_SECRET_ROTATION_ENABLED:=true}${q:='}
      OIDC_SECRET_ROTATION_PERIOD_DAYS: ${q:='}${OIDC_SECRET_ROTATION_PERIOD_DAYS:=90}${q:='}
      OIDC_SECRET_KEY_ALIASES: ${q:='}${OIDC_SECRET_KEY_ALIASES}${q:='}
      emptyArray: "[]"
      emptyDict: "{}"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ${NAMESPACE}
  timeout: 5m
  wait: false
