---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: forgejo-status
spec:
  type: gitea
  address: http://forgejo-http.dev.svc.cluster.local:3000/hayden/phoebe
  secretRef:
    name: forgejo-status-token-secret
