apiVersion: v1alpha1
kind: CRICustomizationConfig
name: 20-customization
content: |
  [plugins."io.containerd.cri.v1.images"]
    discard_unpacked_layers = false
  [plugins."io.containerd.cri.v1.runtime"]
    cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
    device_ownership_from_security_context = true
