apiVersion: v1alpha1
kind: KubeletConfig
clusterDNS:
  - 172.19.0.53
defaultRuntimeSeccompProfileEnabled: true
config:
  featureGates:
    ResourceHealthStatus: true
  serializeImagePulls: false
  allowedUnsafeSysctls:
    - net.ipv6.conf.eth0.disable_ipv6   # needed for matter/thread
    - net.ipv6.conf.net1.*              # needed for matter/thread
    - net.ipv6.conf.all.forwarding      # needed for matter/thread
    - net.ipv6.conf.default.forwarding  # needed for matter/thread
  maxPods: 256
