---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nextcloud
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.0.3
  url: oci://ghcr.io/nextcloud/helm/nextcloud
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nextcloud
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    nextcloud:
      host: drive.hayden.moe
      trustedDomains: [drive.hayden.moe]
      configs:
        custom.config.php: |
          <?php
            $CONFIG = array(
              "allow_local_remote_servers" => true,
              "check_data_directory_permissions" => false, # fix data directory permissions error
              "trusted_domains" => array (
                $_ENV["NEXTCLOUD_TRUSTED_DOMAINS"], # fix probes 400 error
              ),
              'trusted_proxies' => array(
                0 => '127.0.0.1',
                1 => '10.0.0.0/8',
              ),
              "forwarded_for_headers" => array("HTTP_X_FORWARDED_FOR"),
              "overwriteprotocol" => "https",
            );
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: username
        passwordKey: password
      objectStore:
        s3:
          enabled: true
          region: auto
          existingSecret: nextcloud-secret
          secretKeys:
            host: s3Host
            accessKey: s3AccessKey
            secretKey: s3SecretKey
            bucket: s3Bucket
    cronjob:
      enabled: true
    collabora:
      enabled: true
      image:
        tag: 25.04.4.1.1
      collabora:
        aliasgroups: 
          - host: https://drive.hayden.moe:443
        extra_params: --o:ssl.enable=false --o:ssl.termination=true
        server_name: docs.hayden.moe:443
        existingSecret:
          enabled: true
          secretName: nextcloud-secret
          usernameKey: collaboraUsername
          passwordKey: collaboraPassword
    imaginary:
      enabled: true
    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
      rules:
        enabled: true
    persistence:
      enabled: true
      existingClaim: nextcloud
