---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
spec:
  parentRefs:
  - name: external
    namespace: network
    sectionName: https
  hostnames:
    - drive.hayden.moe
  rules:
    - backendRefs:
        - kind: Service
          name: nextcloud
          namespace: default
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: collabora
spec:
  parentRefs:
  - name: external
    namespace: network
    sectionName: https
  hostnames:
    - docs.hayden.moe
  rules:
    - backendRefs:
        - kind: Service
          name: nextcloud-collabora
          namespace: default
          port: 9980
      matches:
        - path:
            type: PathPrefix
            value: /
