---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: konflate-secret
    creationPolicy: Owner
    template:
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .webhookSecret }}"
        KONFLATE_WRITE_TOKEN: "{{ .forgejo_forgejoToken }}"
  dataFrom:
    - extract:
        key: app-konflate
    - extract:
        key: app-forgejo-bot
      rewrite:
        - regexp:
            source: '(.*)'
            target: "forgejo_$1"
