# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
spec:
  chartRef:
    kind: OCIRepository
    name: konflate
  interval: 1h
  values:
    config:
      repo: forgejo://forgejo.hayden.moe/hayden/phoebe
      statusChecks: true
      prComments: true
      publicUrl: https://konflate.hayden.moe
      mcp: true
    secret:
      existingSecret: konflate-secret
    httpRoute:
      enabled: true
      hostnames:
        - konflate.hayden.moe
      parentRefs:
        - name: external
          namespace: network
    monitoring:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cput: 2000m
        memory: 2Gi
