---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane-gcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crossplane-gcp-wif
    template:
      data:
        credential-configuration.json: "{{ .password | b64dec }}"
  dataFrom:
    - extract:
        key: svc-crossplane-iam-k8s-config
