---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-cloudplatform
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-cloudplatform:v3.0.1
  runtimeConfigRef:
    name: provider-gcp-cloudplatform
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-cloudplatform
spec:
  serviceAccountTemplate:
    metadata:
      name: cp-gcp-cloudplatform

  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /etc/gcp/credential-configuration.json
              volumeMounts:
                - name: gcp-wif-config
                  mountPath: /etc/gcp
                  readOnly: true
          volumes:
            - name: gcp-wif-config
              secret:
                secretName: crossplane-gcp-wif
                items:
                  - key: credential-configuration.json
                    path: credential-configuration.json

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-iam
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-iam:v3.0.1
  runtimeConfigRef:
    name: provider-gcp-iam
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-iam
spec:
  serviceAccountTemplate:
    metadata:
      name: cp-gcp-iam
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /etc/gcp/credential-configuration.json
              volumeMounts:
                - name: gcp-wif-config
                  mountPath: /etc/gcp
                  readOnly: true
          volumes:
            - name: gcp-wif-config
              secret:
                secretName: crossplane-gcp-wif
                items:
                  - key: credential-configuration.json
                    path: credential-configuration.json

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-storage
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-storage:v3.0.1
  runtimeConfigRef:
    name: provider-gcp-storage
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-storage
spec:
  serviceAccountTemplate:
    metadata:
      name: cp-gcp-storage
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /etc/gcp/credential-configuration.json
              volumeMounts:
                - name: gcp-wif-config
                  mountPath: /etc/gcp
                  readOnly: true
          volumes:
            - name: gcp-wif-config
              secret:
                secretName: crossplane-gcp-wif
                items:
                  - key: credential-configuration.json
                    path: credential-configuration.json

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.10.3

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-go-templating:v0.12.3
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready:v0.6.3
