---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-cloudplatform
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-cloudplatform:v3.0.1
  runtimeConfigRef:
    name: provider-gcp-cloudplatform
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-cloudplatform
spec:
  serviceAccountTemplate:
    metadata:
      name: cp-gcp-cloudplatform

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-iam
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-iam:v3.0.1
  runtimeConfigRef:
    name: provider-gcp-iam
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-iam
spec:
  serviceAccountTemplate:
    metadata:
      name: cp-gcp-iam

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-storage
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-storage:v3.0.1
  runtimeConfigRef:
    name: provider-gcp-storage
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-storage
spec:
  serviceAccountTemplate:
    metadata:
      name: cp-gcp-storage
