---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    ingress:
      - host: "*.hayden.moe"
        service: https://external
        originRequest:
          noTLSVerify: true
          http2Origin: true
          httpHostHeader: ""
