---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: "${APP}"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      redis:
        containers:
          app:
            image:
              repository: redis
              tag: ${REDIS_VERSION:-8.2.1}-alpine
            command:
              - redis-server
              - --save
              - '60'
              - '1'
              - '--loglevel'
              - 'warning'
            ports:
              - name: redis
                containerPort: 6379
                protocol: TCP
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 6379
                  initialDelaySeconds: 20
                  timeoutSeconds: 5
                  periodSeconds: 5
                  failureThreshold: 5
                  successThreshold: 1
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: [redis-cli, ping]
                  initialDelaySeconds: 10
                  timeoutSeconds: 5
                  periodSeconds: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 1000m
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: redis
        ports:
          redis:
            port: 6379

    persistence:
      data:
        existingClaim: ${APP}
      tmp:
        type: emptyDir
