---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.hayden.moe
      recordType: CNAME
      targets:
        - 3ab5200f-b8e4-46c7-b376-1e37cb90e972.cfargotunnel.com
