---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-token
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-renovate
    template:
      type: Opaque
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - extract:
        key: app-forgejo-bot

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-webhook
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-webhook
    template:
      data:
        webhook: "{{ .password }}"
  dataFrom:
    - extract:
        key: app-renovate-webhook
