---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-token
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-renovate
    template:
      type: Opaque
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .forgejoToken }}"
        RENOVATE_GITHUB_COM_TOKEN: "{{ .token }}"
        RENOVATE_GITHUB_COM_USER: "phoebe-bot"

        RENOVATE_HOST_RULES: |
          [
            {
              "matchHost": "atcr.io",
              "username": "{{ .atcr_username }}",
              "password": "{{ .atcr_password }}"
            },
            {
              "matchHost": "forgejo.hayden.moe",
              "username": "{{ .username }}",
              "password": "{{ .forgejoToken }}",
            }
          ]

  dataFrom:
    - extract:
        key: app-forgejo-bot
    - extract:
        key: svc-atcr
      rewrite:
        - regexp:
            source: '(.*)'
            target: "atcr_$1"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: github-auth-token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-webhook
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-webhook
    template:
      data:
        webhook: "{{ .password }}"
  dataFrom:
    - extract:
        key: app-renovate-webhook
