op_run    := "op run --env-file=.env.op"
plan_file := "plan.tfplan"

plan:
  {{op_run}} -- terraform plan -out={{plan_file}}

apply: plan
  {{op_run}} -- terraform apply {{plan_file}}

import res id:
  {{op_run}} --no-masking -- terraform import {{ res }} {{ id }}

init:
  {{op_run}} -- terraform init
