---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: BackupConfig
metadata:
  name: "${APP}-backup"
spec:
  repository:
    kind: ClusterRepository
    name: hetzner
  sources:
    - pvc:
        name: "${APP}"
  retention:
    keepHourly: 24
    keepDaily: 7

---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: BackupSchedule
metadata:
  name: "${APP}-schedule"
spec:
  configRef:
    name: "${APP}-backup"
  schedule:
    cron: "H * * * *"
    jitter: 30m
    runOnCreate: false

---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: "${APP}-restore"
spec:
  repository:
    kind: ClusterRepository
    name: hetzner
  source:
    fromConfig:
      name: "${APP}-backup"
      offset: 0
  policy:
    onMissingSnapshot: Continue
