---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uhf
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      uhf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: swapplications/uhf-server
              tag: 1.5.1
            command:
              - uhf-server
              - --port
              - &port '8000'
              - --recordings-dir
              - /media/recordings
              - --enable-commercial-detection
            env:
              TZ: Europe/London
              RECORDINGS_DIR: /media/recordings
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        controller: uhf
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.hayden.moe"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: http
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: uhf
        advancedMounts:
          uhf:
            app:
              - path: /var/lib/uhf-server
      media:
        type: nfs
        server: 192.168.1.2
        path: /volume1/media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
