---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-secret
    template:
      data:
        OPENCODE_API_KEY: '{{ .ocg_token }}'
        OPENROUTER_API_KEY: '{{ .or_token }}'
        LITELLM_MASTER_KEY: '{{ .masterKey }}'
  dataFrom:
    - extract:
        key: app-litellm

    - extract:
        key: svc-opencode-go
      rewrite:
        - regexp:
            source: "(.*)"
            target: ocg_$1

    - extract:
        key: svc-openrouter
      rewrite:
        - regexp:
            source: "(.*)"
            target: or_$1
