---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-secret
    template:
      data:
        OPENROUTER_API_KEY: '{{ .or_token }}'
        CHARM_HYPER_API_KEY: '{{ .hyper_token }}'
        LITELLM_MASTER_KEY: '{{ .masterKey }}'
  dataFrom:
    - extract:
        key: app-litellm

    - extract:
        key: svc-openrouter
      rewrite:
        - regexp:
            source: "(.*)"
            target: or_$1

    - extract:
        key: svc-charm-hyper
      rewrite:
        - regexp:
            source: "(.*)"
            target: hyper_$1
