---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmproxy_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMProxy
metadata:
  name: litellm
spec:
  # renovate: datasource=docker depName=ghcr.io/berriai/litellm
  image: ghcr.io/berriai/litellm:v1.99.1@sha256:a53a7d3ffebede1925bd3ee8a21e4a7b9b63e2e68ec883af136edcccb6eeb82c
  replicas: 1

  applyMode: api
  apiAccess:
    masterKeyRef:
      name: litellm-secret
      key: LITELLM_MASTER_KEY

  generalSettings:
    health_check_endpoint: /v1/health

  litellmSettings:
    success_callback: ["prometheus"]
    prometheus_adapter: true
    cache: default_off
    cache_params:
      type: redis
      host: os.environ/REDIS_HOST
      port: os.environ/REDIS_PORT
    drop_params: true
    merge_reasoning_content_in_choices: true
    set_verbose: false
    require_auth_for_metrics_endpoint: false

  podAnnotations:
    reloader.stakater.com/auto: "true"

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: litellm

  volumeMounts:
    - name: data
      mountPath: /app/chatgpt_tokens
      subPath: chatgpt-tokens

  envFrom:
    - secretRef:
        name: litellm-secret

  env:
    - name: CHATGPT_TOKEN_DIR
      value: /app/chatgpt_tokens

    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: litellm-postgres
          key: url

    - name: LITELLM_LOG
      value: INFO

    - name: REDIS_HOST
      value: dragonfly.database.svc

    - name: REDIS_PORT
      value: "6379"

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 4Gi

  service:
    type: ClusterIP
    port: 4000

  route:
    hostnames:
      - llm.hayden.moe
    parentRefs:
      - name: external
        namespace: network
