---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: chatgpt-gpt-5.6-luna
spec:
  modelName: chatgpt/gpt-5.6-luna
  params:
    model: chatgpt/gpt-5.6-luna
  info:
    mode: responses

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: chatgpt-gpt-5.6-terra
spec:
  modelName: chatgpt/gpt-5.6-terra
  params:
    model: chatgpt/gpt-5.6-terra
  info:
    mode: responses

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: chatgpt-gpt-5.6-sol
spec:
  modelName: chatgpt/gpt-5.6-sol
  params:
    model: chatgpt/gpt-5.6-sol
  info:
    mode: responses
