---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: context7-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: context7-api-key
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: mcp-context7
        property: token

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homeassistant-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: mcp-home-assistant
        property: token
