# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmservicescrape_v1beta1.json
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: litellm
  labels:
    job: litellm
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
