---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: garage-operator-secret
    template:
      data:
        rpc-secret: "{{ .GARAGE_RPC_SECRET }}"
        admin-token: "{{ .GARAGE_ADMIN_TOKEN }}"
        metrics-token: "{{ .GARAGE_METRICS_TOKEN }}"
  dataFrom:
    - extract:
        key: app-garage
