---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage
  annotations:
    gatus.home-operations.com/endpoint: |-
      conditions: ["[STATUS] == 403"]
spec:
  hostnames:
    - s3.hayden.moe
  parentRefs:
    - name: external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: garage
          port: 3900

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-static
  annotations:
    gatus.home-operations.com/endpoint: |-
      conditions: ["[STATUS] == 403"]
spec:
  hostnames:
    - '*.s3.hayden.moe'
  parentRefs:
    - name: external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: garage
          port: 3902
