---
working_dir: ./docker/vps
reconciliation:
  enabled: true
auto_discovery:
  enabled: true
  depth: 1
  delete: true
force_recreate: false
external_secrets:
  VPS_IP: "op://cluster-phoebe/app-towonel/ip"
  TOWONEL_ACME_EMAIL: "op://cluster-phoebe/app-towonel/acmeEmail"
  TOWONEL_INVITE_HASH_KEY: "op://cluster-phoebe/app-towonel/inviteHashKey"
  TOWONEL_OPERATOR_KEY: "op://cluster-phoebe/app-towonel/operatorKey"
