---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mimi
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kopiur
    - ../../../../components/kanidm/private
  interval: 1h
  path: ./kubernetes/apps/ai/mimi/app
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace

      OIDC_DISPLAY_NAME: Mimi Dashboard
      OIDC_IMAGE_URL: 'https://cdn.discordapp.com/avatars/1522274117813014802/6f8f834b655989a6c704313515563e57?size=256'
      OIDC_ORIGIN: https://mimi.hayden.moe
      OIDC_SECRET_ROTATION_ENABLED: 'false'
      OIDC_PUBLIC: 'true'
      OIDC_REDIRECT_URLS: '[https://mimi.hayden.moe/auth/callback]'
      OIDC_USERS_GROUP_MEMBERS: '[hayden]'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
