---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: clickhouse-cluster
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputStrategy:
    name: Permute
  inputs:
    - user: internal
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      selector:
        matchLabels:
          clickhouse.hayden.moe/role: "true"
  resourcesTemplate: |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: &app clickhouse-cluster
      namespace: &namespace database
    spec:
      commonMetadata:
        labels:
          app.kubernetes.io/name: *app
      healthChecks:
        - apiVersion: clickhouse.com/v1alpha1
          kind: ClickHouseCluster
          name: clickhouse
          namespace: database
      interval: 1h
      path: ./kubernetes/apps/database/clickhouse/cluster
      prune: true
      retryInterval: 2m
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      targetNamespace: *namespace
      timeout: 5m
      patches:
        - target:
            kind: ClickHouseCluster
            group: clickhouse.com
            version: v1alpha1
          patch: |-
            apiVersion: clickhouse.com/v1alpha1
            kind: ClickHouseCluster
            metadata:
              name: not-used
            spec:
              containerTemplate:
                env:
                  <<- $userMap := dict >>
                  <<- range $k, $in := inputs >>
                  <<-   if kindIs "map" $in >>
                  <<-     $u := index $in "user" >>
                  <<-     if $u >>
                  <<-       $_ := set $userMap $u $in >>
                  <<-     end >>
                  <<-   end >>
                  <<- end >>

                  <<- $userNames := keys $userMap | sortAlpha >>

                  <<- $userEnvs := list >>

                  <<- range $u := $userNames >>
                  <<-   $in := index $userMap $u >>
                  <<-   $env := print ($u | upper) "_PASSWORD" >>
                  <<-   $user := dict "name" $env "valueFrom" (dict "secretKeyRef" (dict "name" (print $u "-clickhouse") "key" "password")) >>
                  <<-   $userEnvs := concat $userEnvs (list $user) >>
                  <<- end >>

                  <<- toYaml $userObjs | nindent 18 >>

              settings:
                extraUsersConfig:
                  <<- $userMap := dict >>
                  <<- range $k, $in := inputs >>
                  <<-   if kindIs "map" $in >>
                  <<-     $u := index $in "user" >>
                  <<-     if $u >>
                  <<-       $_ := set $userMap $u $in >>
                  <<-     end >>
                  <<-   end >>
                  <<- end >>

                  <<- $userNames := keys $userMap | sortAlpha >>

                  <<- $userObjs := dict >>

                  <<- range $u := $userNames >>
                  <<-   $in := index $userMap $u >>

                  <<-   $password := (list (dict "@from_env" (print ($u | upper) "_PASSWORD"))) >>

                  <<-   $profile := "readwrite" >>
                  <<-   $pVal := index $in "profile" | toString | lower >>

                  <<-   $quota := "default" >>
                  <<-   $qVal := index $in "quota" | toString | lower >>

                  <<-   $user := dict "profile" $profile "quota" $quota "password" $password >>

                  <<-   $_ := set $userObjs $u $user >>
                  <<- end >>

                  <<- toYaml (dict "users" $userObjs) | nindent 18 >>
