---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: towonel-agent-secret
    template:
      data:
        TOWONEL_INVITE_TOKEN: "{{ .token }}"
  dataFrom:
    - extract:
        key: towonel-agent
