---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: memini-secret
    template:
      data:
        MEMINI_API_KEY: "{{ .apiKey }}"
  dataFrom:
    - extract:
        key: app-memini
