---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discolinear-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: discolinear-secret
    template:
      data:
        DISCORD_TOKEN: "{{ .DISCORD_TOKEN }}"
        LINEAR_TOKEN: "{{ .LINEAR_TOKEN }}"
  dataFrom:
    - extract:
        key: discolinear
