---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextpvr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      nextpvr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: nextpvr/nextpvr_amd64
              tag: stable@sha256:b5c2908e786b969318dcd2f52dde484713149c2abaf30b641c482a7a4cc9e31b
            env:
              TZ: Europe/London
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    # service:
    #   app:
    #     controller: nextpvr
    #     ports:
    #       http:
    #         port: *port
    # route:
    #   app:
    #     hostnames: ["{{ .Release.Name }}.hayden.moe"]
    #     parentRefs:
    #       - name: internal
    #         namespace: kube-system
    #         sectionName: https
    #     rules:
    #       - backendRefs:
    #           - identifier: app
    #             port: *port
    persistence:
      data:
        existingClaim: nextpvr
        globalMounts:
          - path: /config
            subPath: config
          - path: /buffer
            subPath: buffer
      media:
        type: nfs
        server: 192.168.1.2
        path: /volume1/media
        globalMounts:
          - path: /recordings
            subPath: livetv
      tmp:
        type: emptyDir
