---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./httproute.yaml
configMapGenerator:
  - name: forgejo-themes
    files:
      - ./resources/themes/theme-gitdotgay.css
      - ./resources/themes/theme-gitdotgay-dark.css
      - ./resources/themes/theme-gitdotgay-light.css
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
