---
apiVersion: v1
kind: Namespace
metadata:
  name: discolinear
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discolinear
  namespace: argocd
spec:
  project: discolinear
  source:
    path: ./kubernetes/apps/argocd/argocd/deploy/applications/discolinear
    repoURL: https://github.com/hbjydev/phoebe
    targetRevision: main
  destination:
    namespace: discolinear
    server: 'https://kubernetes.default.svc'
