---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  chartRef:
    kind: OCIRepository
    name: kopiur
  interval: 30m
  values:
    installScope: cluster
    webhook:
      certManager:
        enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    grafanaDashboard:
      enabled: true
      grafanaOperator:
        enabled: true
        matchLabels:
          grafana.internal/instance: grafana
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    secretProjection:
      enabled: true
    logging:
      level: info,kopia=debug
      format: json
