---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: &name ts-srv-phoebe
spec:
  replicas: 1
  hostnamePrefix: *name
  tags:
    - "tag:phoebe-gw"
  subnetRouter:
    advertiseRoutes:
      - "172.18.0.0/16"  # pods
      - "172.19.0.0/16"  # services
