[SERVICE]
    flush           5
    log_level       warn
    parsers_file    /fluent-bit/etc/parsers.conf

[INPUT]
    name            tail
    path            /var/lib/docker/containers/*/*.log
    path_key        container_path
    parser          docker
    tag             docker.*
    docker_mode     on
    docker_mode_flush 5
    db              /fluent-bit/data/tail.db
    skip_empty_lines on
    refresh_interval 10

[FILTER]
    name            lua
    match           docker.*
    script          /fluent-bit/etc/enrich.lua
    call            enrich

[FILTER]
    name            grep
    match           docker.*
    exclude         container_name ^fluent-bit$

[OUTPUT]
    name                 http
    match                docker.*
    host                 victorialogs
    port                 443
    uri                  /insert/jsonline?_stream_fields=stream,container_name,host&_msg_field=log&_time_field=date
    format               json_lines
    json_date_format     iso8601
    compress             gzip
    log_response_payload false
