---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: actual-secret
    template:
      data:
        ACTUAL_OPENID_DISCOVERY_URL: https://sso.hayden.moe/oauth2/openid/{{ .clientId }}/.well-known/openid-configuration
        ACTUAL_OPENID_CLIENT_ID: '{{ .clientId }}'
        ACTUAL_OPENID_CLIENT_SECRET: '{{ .clientSecret }}'
        ACTUAL_OPENID_SERVER_HOSTNAME: 'https://actual.hayden.moe'
  dataFrom:
    - extract:
        key: app-actual
