---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tandoor-secret
    template:
      data:
        # App
        SECRET_KEY: "{{ .secretKey }}"

        # OIDC
        SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
                "OAUTH_PKCE_ENABLED": true,
                "APPS": [
                    {
                        "provider_id": "sso",
                        "name": "SSO",
                        "client_id": "tandoor",
                        "secret": "{{ .clientSecret }}",
                        "settings": {
                            "server_url": "https://sso.hayden.moe/oauth2/openid/tandoor/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
  dataFrom:
    - extract:
        key: app-tandoor
