---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: hetzner
spec:
  backend:
    s3:
      bucket: phoebe-backup
      prefix: "kopiur"
      endpoint: hel1.your-objectstorage.com
      region: US
      auth:
        secretRef:
          name: kopia-secret
          namespace: kopiur-system

  create:
    enabled: true

  encryption:
    passwordSecretRef:
      name: kopia-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD

  allowedNamespaces:
    all: true

  identityDefaults:
    hostnameExpr: namespace
    usernameExpr: namespace + '-' + policyName

  moverDefaults:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    ttlSecondsAfterFinished: 86400

  maintenance:
    namespace: kopiur-system
