---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-hetzner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "kopia-hetzner-secret"
    template:
      data:
        KOPIA_PASSWORD: "{{ .password }}"
        AWS_ACCESS_KEY_ID: "{{ .accessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
  dataFrom:
    - extract:
        key: svc-hetzner-backup
