---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: discolinear
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  description: Discolinear
  sourceRepos: ['*']
  destinations:
    - namespace: discolinear
      server: https://kubernetes.default.svc
