---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: unifi-dns-secret
    template:
      data:
        UNIFI_API_KEY: "{{ .apiKey }}"
  dataFrom:
    - extract:
        key: unifi
