---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mimi-secret
    template:
      data:
        LIVVI_DISCORD_TOKEN: "{{ .discordBotToken }}"
        LIVVI_MEMINI_API_KEY: "{{ .memini_apiKey }}"
        LIVVI_OPENAI_API_KEY: "{{ .litellmKey }}"
  dataFrom:
    - extract:
        key: app-mimi

    - extract:
        key: app-memini
      rewrite:
        - regexp:
            source: "(.*)"
            target: memini_$1
