---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimi-config-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mimi-config-env
    template:
      data:
        API_SERVER_KEY: '{{ .apiServerKey }}'

        DISCORD_HOME_CHANNEL: '1525540932043411548'
        DISCORD_HOME_CHANNEL_NAME: '#general'
        DISCORD_BOT_TOKEN: '{{ .discordBotToken }}'

        KIMI_API_KEY: "{{ .kimi_token }}"
        SEARXNG_URL: http://searxng.selfhosted:8080
        MEMINI_API_KEY: "{{ .memini_apiKey }}"
  dataFrom:
    - extract:
        key: app-mimi

    - extract:
        key: app-memini
      rewrite:
        - regexp:
            source: "(.*)"
            target: memini_$1

    - extract:
        key: svc-kimi
      rewrite:
        - regexp:
            source: "(.*)"
            target: kimi_$1
