---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimi
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      mimi:
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1
        strategy: Recreate
        type: deployment

        containers:
          mimi:
            image:
              repository: ghcr.io/hbjydev/livvi
              tag: bc524a5@sha256:d7c73906390ce0653a6982d3392053e22af3ec5172eae9ec617b06aaa989f098
            env:
              RUST_LOG: info
              LIVVI_MEMINI_BASE_URL: http://memini.ai:8080
              LIVVI_MEMINI_NAMESPACE: mimi
              LIVVI_OPENAI_API_URL: http://litellm.ai:4000
              LIVVI_OPENAI_MODEL_NAME: ms-kimi-k2.7
              LIVVI_DATABASE_URL: sqlite:/data/livvi.db?mode=rwc
              LIVVI_LCM_DATABASE_URL: sqlite:/data/lcm.db?mode=rwc

              OTEL_TRACES_SAMPLER: traceidratio
              OTEL_TRACES_SAMPLER_ARG: '0.5'
              OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://vmsingle-victoria-metrics.observability.svc:8428/opentelemetry/v1/metrics'
              OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://vtsingle-victoria-traces.observability.svc:10428/insert/opentelemetry/v1/traces'
            envFrom:
              - secretRef:
                  name: mimi-secret
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always

    persistence:
      data:
        existingClaim: '{{ .Release.Name }}'

      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
