---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: forgejo
spec:
  groupRef:
    name: mcp-tools
  image: codeberg.org/goern/forgejo-mcp:v2.30.1
  transport: streamable-http
  secrets:
    - name: toolhive-servers
      key: FORGEJO_TOKEN
      targetEnvName: FORGEJO_ACCESS_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          args:
            - "--transport"
            - "http"
            - "--http-port"
            - "8080"
            - "--url"
            - "http://forgejo-http.dev.svc.cluster.local:3000"
          ports:
            - containerPort: 8080
              name: mcp
