---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-cert-upload
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      unifi-cert-upload:
        type: cronjob
        cronjob:
          schedule: "0 * * * *"
          failedJobsHistory: 3
          successfulJobsHistory: 1
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            egress.policy.home.arpa/infra: "true"
            egress.policy.home.arpa/internet: "true"
        containers:
          app:
            image:
              repository: mirror.gcr.io/rockylinux/rockylinux
              tag: 10@sha256:827d37bc128288ccf160ee318bb3cb92d591164cb217e92f8bc61e3982ae1834
            command:
              - /bin/bash
              - -ec
              - |
                #!/usr/bin/env bash
                set -euo pipefail

                base_url="https://10.70.0.1"
                username="${UNIFI_USERNAME}"
                password="${UNIFI_PASSWORD}"

                cert_pem="$(cat /certs/tls.crt | awk '{printf "%s\\n", $0}')"
                key_pem="$(cat /certs/tls.key | awk '{printf "%s\\n", $0}')"

                date="$(date +%Y%m%d%H%M)"

                token=""
                csrf_token=""

                fatal() {
                  local msg="${1}"
                  echo "[FATAL] ${msg}"
                  exit 1
                }

                login() {
                  resp="$(curl -k -X POST "${base_url}/api/auth/login" \
                    -H "Content-Type: application/json" \
                    -d "{\"username\":\"${username}\",\"password\":\"${password}\"}" \
                    -i)"

                  token="$(echo "${resp}" | grep -i 'set-cookie: TOKEN=' | awk -F= '{print $2}' | awk -F';' '{print $1}' | tr -d '\r')"
                  csrf_token="$(echo "${resp}" | grep -i 'x-csrf-token: ' | awk '{print $2}')"
                }

                get() {
                  resp="$(curl -k -X GET "${base_url}${1}" \
                    -H "Content-Type: application/json" \
                    -H "Cookie: TOKEN=${token}" \
                    -H "x-csrf-token: ${csrf_token}")"

                  echo "${resp}"
                }

                post() {
                  resp="$(curl -k -X POST "${base_url}${1}" \
                    -H "Content-Type: application/json" \
                    -H "Cookie: TOKEN=${token}" \
                    -H "x-csrf-token: ${csrf_token}" \
                    -d "${2}")"

                  echo "${resp}"
                }

                put() {
                  resp="$(curl -k -X PUT "${base_url}${1}" \
                    -H "Content-Type: application/json" \
                    -H "Cookie: TOKEN=${token}" \
                    -H "x-csrf-token: ${csrf_token}" \
                    -d "${2}")"

                  echo "${resp}"
                }

                echo "[INFO ] Installing JQ..."
                dnf install -y jq

                echo "[INFO ] Logging into UniFi"
                login || fatal "Failed to log in"
                echo "[INFO ] Uploading new certificate"
                id=$(post /api/userCertificates '{"name":"le-'"${date}"'","cert":"'"${cert_pem}"'","key":"'"${key_pem}"'"}' | jq -r .id)
                echo "[INFO ] Activating certificate"
                put "/api/userCertificates/${id}/status" '{"active":true}' || fatal "Failed to activate new certificate"
                echo "[INFO ] Complete"
            env:
              TZ: Europe/London
            envFrom:
              - secretRef:
                  name: unifi-cert-upload-secret
            securityContext:
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      certs:
        type: secret
        name: hayden-moe-tls
        defaultMode: 0o600
