---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: Folder
metadata:
  name: fldr-$(BASE_NAMESPACE)
spec:
  forProvider:
    displayName: fldr-$(BASE_NAMESPACE)
    parentRef:
      name: fldr-phoebe
  providerConfigRef:
    name: gcp-cloudplatform
