---
varReference:
  - group: cloudplatform.gcp.upbound.io
    version: v1beta1
    kind: Folder
    path: metadata/name

  - group: cloudplatform.gcp.upbound.io
    version: v1beta1
    kind: Folder
    path: spec/forProvider/displayName
