---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./namespace.yaml
  - ./folder.yaml
  - ./secrets.yaml
  - ./alerts
  - ./repos
  - ./sops

vars:
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: Namespace
      name: not-used
    fieldref:
      fieldpath: metadata.name

configurations:
  - ./kustomizeconfig.yaml
