---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tvheadend
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tvheadend:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/tvheadend/tvheadend
              tag: master-debian@sha256:97f27c92c793688ae719cd95b348e835787fda62ea74aa5f9d0a09354bfb0353
            env:
              TZ: Europe/London
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi
            ports:
              - containerPort: &port 9981
                protocol: tcp
              - containerPort: 9982
                protocol: tcp
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: tvheadend
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.hayden.moe"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: tvheadend
        globalMounts:
          - path: /var/lib/tvheadend
      media:
        type: nfs
        server: 192.168.1.2
        path: /volume1/media
        globalMounts:
          - path: /var/lib/tvheadend/recordings
            subPath: live
      tmp:
        type: emptyDir
