---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-config-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes-config-env
    template:
      data:
        API_SERVER_KEY: '{{ .apiServerKey }}'

        DISCORD_ALLOWED_USERS: '{{ .discordAllowedUsers }}'
        DISCORD_HOME_CHANNEL: '1515119754602352791'
        DISCORD_HOME_CHANNEL_NAME: '#holly'
        DISCORD_BOT_TOKEN: '{{ .discordBotToken }}'

        LITELLM_API_KEY: '{{ .litellmKey }}'
        HASS_TOKEN: '{{ .hassToken }}'
        SEERR_API_KEY: '{{ .js_apiKey }}'
        FORGEJO_URL: '{{ .forgejoUrl }}'
        FORGEJO_USERNAME: '{{ .forgejoUsername }}'
        FORGEJO_TOKEN: '{{ .forgejoToken }}'
        SEARXNG_URL: http://searxng.selfhosted:8080
        MEMINI_API_KEY: "{{ .memini_apiKey }}"
  dataFrom:
    - extract:
        key: app-hermes

    - extract:
        key: app-memini
      rewrite:
        - regexp:
            source: "(.*)"
            target: memini_$1

    - extract:
        key: app-jellyseerr
      rewrite:
        - regexp:
            source: "(.*)"
            target: js_$1
