---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-config-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes-config-env
    template:
      data:
        HERMES_DASHBOARD_OIDC_ISSUER: https://sso.hayden.moe/oauth2/openid/hermes
        HERMES_DASHBOARD_OIDC_CLIENT_ID: hermes

        API_SERVER_ENABLED: 'true'
        API_SERVER_HOST: 0.0.0.0
        API_SERVER_KEY: '{{ .apiServerKey }}'
        API_SERVER_CORS_ORIGINS: '*'

        DISCORD_ALLOWED_ROLES: '1515307160744099900,1515307305673953391'
        DISCORD_HOME_CHANNEL: '1515119754602352791'
        DISCORD_HOME_CHANNEL_NAME: '#holly'
        DISCORD_BOT_TOKEN: '{{ .discordBotToken }}'

        OPENCODE_GO_API_KEY: '{{ .ocg_token }}'
        OPENROUTER_API_KEY: '{{ .or_token }}'
  dataFrom:
    - extract:
        key: app-hermes

    - extract:
        key: svc-opencode-go
      rewrite:
        - regexp:
            source: "(.*)"
            target: ocg_$1

    - extract:
        key: svc-openrouter
      rewrite:
        - regexp:
            source: "(.*)"
            target: or_$1
