---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: hermes
spec:
  displayname: Hermes Agent
  public: true
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/hermes-agent.png
  kanidmRef:
    name: kanidm
    namespace: security
  origin: https://hermes.hayden.moe
  redirectUrl:
    - https://hermes.hayden.moe/auth/callback
  preferShortUsername: true

  scopeMap:
    - group: hermes_users
      scopes:
        - openid
        - profile
        - email
        - groups

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: hermes-users
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  kanidmName: hermes_users
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - hayden
