---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-github-app-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "eso-github-app-pem"
    template:
      data:
        key: "{{ .privateKey | b64dec }}"
  dataFrom:
    - extract:
        key: svc-github
