---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: github-auth-token
spec:
  kind: GithubAccessToken
  generator:
    githubAccessTokenSpec:
      appID: '1354746'
      installID: '69322391'
      auth:
        privateKey:
          secretRef:
            namespace: external-secrets
            name: eso-github-app-pem
            key: key
