---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
spec:
  chartRef:
    kind: OCIRepository
    name: signoz
  interval: 30m
  values:
    global:
      storageClass: ceph-block
      clusterName: phoebe

    fullnameOverride: signoz

    clickhouse:
      installCustomStorageClass: false

    signoz:
      name: signoz
      replicaCount: 1
      image:
        repository: signoz/signoz
        # renovate: datasource=github-releases depName=signoz/signoz
        tag: v0.127.0

      env:
        signoz_emailing_enabled: true
