---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmpodscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: envoy-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/component: proxy
  jobLabel: envoy-proxy
  namespaceSelector:
    matchNames:
      - network
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      honorLabels: true

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: envoy-proxy
spec:
  selector:
    matchLabels:
      control-plane: envoy-gateway
  jobLabel: envoy-gateway
  namespaceSelector:
    matchNames:
      - network
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
