---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openclaw-secret
    template:
      data:
        OPENCLAW_GATEWAY_PASSWORD: '{{ .password }}'
        MEMINI_API_KEY: "{{ .memini_apiKey }}"
  dataFrom:
    - extract:
        key: app-openclaw
    - extract:
        key: app-memini
      rewrite:
        - regexp:
            source: "(.*)"
            target: memini_$1
