---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-misc
  namespace: ai
  labels:
    app.kubernetes.io/name: openclaw
    kustomize.toolkit.fluxcd.io/prune: "Disabled"
spec:
  storageClassName: "ceph-block"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: "50Gi"
