---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:7259c775ce18bdf668f17a68accb78e5bcc8074bbea9c8cdac974a8a8525a173

  certificates:
    serverTLSSecret: postgres-server-cert
    serverCASecret: postgres-server-cert
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-replication-cert

  storage:
    size: 24Gi
    storageClass: ceph-block

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store barman-hetzner

  externalClusters:
    - name: &src source
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: hayden-postgres

  monitoring:
    enablePodMonitor: true

  postgresql:
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map
      - host all all all scram-sha-256
    pg_ident:
      - pooler-map pooler-rw all
    shared_preload_libraries:
      - "vchord"
      - "timescaledb"
    parameters:
      timescaledb.telemetry_level: "off"
      max_locks_per_transaction: "128"

    extensions:
      - name: postgis
        ld_library_path:
          - system
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension-testing:3.6.3-18-trixie@sha256:0f0c9b137b62b2332b72fa97af4991c28c2ca283429e79619a5ed357986d2b84
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
      - name: timescaledb
        image:
          reference: ghcr.io/shusaan/timescaledb-testing:2.24.0-18-trixie@sha256:dae25c2dde06455214ac5553b51d3ef2d48fe84795c2cfa48c51c6e15877044e

  managed:
    roles:
      - name: pooler-rw
        ensure: present
        login: true
        superuser: false
        disablePassword: true
