---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: barman-hetzner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "barman-hetzner-secret"
    template:
      data:
        ACCESS_KEY_ID: "{{ .accessKeyId }}"
        SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
  dataFrom:
    - extract:
        key: svc-hetzner-backup
