---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      paperless:
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.19.3
            env:
              PAPERLESS_URL: https://paperless.hayden.moe
              PAPERLESS_PORT: &port 8000
              PAPERLESS_TIME_ZONE: Europe/London
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"

              # Redis Config
              PAPERLESS_REDIS: "redis://paperless-redis:6379"

              # Folders
              PAPERLESS_DATA_DIR: /mnt/paperless/data
              PAPERLESS_MEDIA_ROOT: /mnt/paperless/media
              PAPERLESS_CONSUMPTION_DIR: /mnt/paperless/incoming
              PAPERLESS_EXPORT_DIR: /mnt/paperless/export

              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"

              # Configure OCR
              PAPERLESS_OCR_LANGUAGE: "eng"

              # Configure SSO
              PAPERLESS_ENABLE_ALLAUTH: "true"
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              PAPERLESS_AUTO_LOGIN: "true"
              PAPERLESS_AUTO_CREATE: "true"
              PAPERLESS_LOGOUT_REDIRECT_URL: "https://sso.hayden.moe/application/o/paperless/end-session/"

              # Permissions
              USERMAP_UID: 1000
              USERMAP_GID: 1000
            envFrom:
              - secretRef:
                  name: paperless-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 2Gi

    service:
      app:
        controller: paperless
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.hayden.moe"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      mnt:
        type: nfs
        server: 192.168.1.2
        path: /volume1/media
      tmp:
        type: emptyDir
