---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grafana-cloud
    template:
      data:
        tenantId: "{{ .stackId }}"
        logsUserId: "{{ .lokiUserId }}"
        mimirUserId: "{{ .mimirUserId }}"
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: grafana-cloud
