---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kanidm-git
spec:
  interval: 1h
  url: https://forgejo.hayden.moe/hayden/kanidm-auth-objects
  ref:
    branch: main
  secretRef:
    name: kanidm-git-auth

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kanidm-git
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: kanidm-git

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-git-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kanidm-git-auth
  data:
    - secretKey: username
      remoteRef:
        key: app-forgejo-bot
        property: user_name

    - secretKey: password
      remoteRef:
        key: app-forgejo-bot
        property: forgejoToken

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/receiver_v1.json
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: kanidm-git-auth-webhook
spec:
  type: github
  events: ["ping", "push"]
  secretRef:
    name: kanidm-git-auth-webhook-token-secret
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: flux-system

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-git-auth-webhook-token-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kanidm-git-auth-webhook-token-secret
    template:
      data:
        token: "{{ .password }}"
  dataFrom:
    - extract:
        key: app-flux-webhook-kanidm
