---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: mimi
      app.kubernetes.io/instance: mimi
      app.kubernetes.io/controller: mimi
    includeSelectors: true
resources:
  - ./instance.yaml
  - ./httproute.yaml
  - ./rbac.yaml

configMapGenerator:
  - name: mimi-mise-config
    files:
      - mise.toml

generatorOptions:
  disableNameSuffixHash: true
