---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tranquil
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tranquil-secret
    template:
      data:
        JWT_SECRET: '{{ .jwtSecret }}'
        DPOP_SECRET: '{{ .dpopSecret }}'
        MASTER_KEY: '{{ .masterKey }}'
  dataFrom:
    - extract:
        key: app-tranquil
    - extract:
        key: strg-ucos-haydenmoe-tranquil-blobs
