---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tranquil
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tranquil-secret
    template:
      data:
        JWT_SECRET: '{{ .jwtSecret }}'
        DPOP_SECRET: '{{ .dpopSecret }}'
        MASTER_KEY: '{{ .masterKey }}'
        BLOB_STORAGE_BACKEND: s3
        AWS_ACCESS_KEY_ID: "{{ .accessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
        S3_BUCKET: '{{ .bucketName }}'
        S3_ENDPOINT: '{{ .endpointPublic }}'
  dataFrom:
    - extract:
        key: app-tranquil
    - extract:
        key: strg-ucos-haydenmoe-tranquil-blobs
