---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tranquil
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      tandoor:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            egress.policy.home.arpa/internet: "true"
            egress.policy.home.arpa/postgres: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: atcr.io/tranquil.farm/tranquil-pds
              tag: 72fa88d79adfd30fb29e330987bb3cb0eb51f310
            env:
              TZ: Europe/London
              PDS_HOSTNAME: at.hayden.moe
              SERVER_HOST: 0.0.0.0
              SERVER_PORT: &port 3000
              PDS_AGE_ASSURANCE_OVERRIDE: true
              INVITE_CODE_REQUIRED: true
              MAIL_FROM_ADDRESS: pds@hayden.moe
              MAIL_FROM_NAME: Hayden's PDS
              DATABASE_URL:
                secretKeyRef:
                  name: tranquil-postgres
                  key: url
              CRAWLERS: https://bsky.network,https://relay.upcloud.world

              # Storage
              BLOB_STORAGE_BACKEND: s3
              S3_BUCKET:
                secretKeyRef:
                  name: tranquil-media-s3
                  key: S3_BUCKET
              S3_ENDPOINT:
                secretKeyRef:
                  name: tranquil-media-s3
                  key: AWS_ENDPOINT_URL
              AWS_ACCESS_KEY_ID:
                secretKeyRef:
                  name: tranquil-media-s3
                  key: AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY:
                secretKeyRef:
                  name: tranquil-media-s3
                  key: AWS_SECRET_ACCESS_KEY
            envFrom:
              - secretRef:
                  name: tranquil-secret
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /xrpc/_health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1024Mi
    defaultPodOptions:
      imagePullSecrets:
        - name: imp-atcr
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      automountServiceAccountToken: true

    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - at.hayden.moe
          - '*.at.hayden.moe'
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    configMaps:
      msmtprc:
        enabled: true
        data:
          msmtprc: |
            defaults

            account relay
            host smtp-relay
            from pds@hayden.moe

            account default: relay

    persistence:
      msmtprc:
        type: configMap
        name: '{{ .Release.Name }}'
        globalMounts:
          - path: /etc/msmtprc
            subPath: msmtprc

      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
