---
apiVersion: infra.hayden.moe/v1alpha1
kind: StorageBucket
metadata:
  name: tranquil-media
  namespace: selfhosted
spec:
  serviceProjectRef:
    name: tranquil
  location: EU
  serviceAccount: tranquil
  role: roles/storage.objectAdmin
  interoperability:
    enabled: true
