---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: operator-oauth
    template:
      data:
        client_id: "{{ .clientId }}"
        client_secret: "{{ .clientSecret }}"
  dataFrom:
    - extract:
        key: tailscale
