---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/inference.llmkube.dev/model_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: all-minilm-l6-v2
spec:
  source: hf://sentence-transformers/all-MiniLM-L6-v2
  format: custom
  hardware:
    accelerator: vulkan
    memoryBudget: 1Gi
  resources:
    cpu: "1"
    memory: 256Mi
  refreshPolicy: OnChange
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/inference.llmkube.dev/inferenceservice_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: all-minilm-l6-v2
spec:
  modelRef: all-minilm-l6-v2
  runtime: vllm
  resources:
    cpu: "1"
    memory: 2Gi
