---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crossplane-gcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crossplane-gcp-secret
    template:
      data:
        credentials.json: "{{ .serviceAccountKeyB64 | b64dec }}"
  dataFrom:
    - extract:
        key: svc-crossplane-gcp
