---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cp-gcp-storage
  namespace: crossplane-system

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cp-gcp-storage
  namespace: crossplane-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cp-gcp-storage
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        credential-configuration.json: "{{ .password | b64dec }}"
  dataFrom:
    - extract:
        key: sa-gcp-crossplane-stg-k8s-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cp-gcp-cloudplatform
  namespace: crossplane-system

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cp-gcp-cloudplatform
  namespace: crossplane-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cp-gcp-cloudplatform
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        credential-configuration.json: "{{ .password | b64dec }}"
  dataFrom:
    - extract:
        key: sa-gcp-crossplane-rm-k8s-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cp-gcp-iam
  namespace: crossplane-system

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cp-gcp-iam
  namespace: crossplane-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cp-gcp-iam
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        credential-configuration.json: "{{ .password | b64dec }}"
  dataFrom:
    - extract:
        key: sa-gcp-crossplane-iam-k8s-config
