---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app huly
  namespace: &namespace huly
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kanidm/private
  interval: 1h
  path: "./kubernetes/apps/huly/huly/app"
  postBuild:
    substitute:
      APP: huly

      OIDC_DISPLAY_NAME: Huly
      OIDC_ORIGIN: https://huly.hayden.moe/
      OIDC_REDIRECT_URLS: '["https://huly.hayden.moe/auth/openid/callback"]'
      OIDC_USERS_GROUP_MEMBERS: '[hayden]'
      OIDC_ADMIN_GROUP_MEMBERS: '[hayden]'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
