---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoria-metrics
spec:
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.147.0
    pullPolicy: Always

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  retentionPeriod: "12"

  storage:
    storageClassName: ceph-block
    resources:
      requests:
        storage: 50Gi
