---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_SECRET_KEY: "{{ .secretKey }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "kanidm",
                  "name": "Hayden's SSO (kanidm)",
                  "client_id": "{{ .kanidm_key }}",
                  "secret": "{{ .kanidm_secret }}",
                  "settings": {
                    "server_url": "https://sso.hayden.moe/oauth2/openid/{{ .kanidm_key }}/.well-known/openid-configuration",
                    "oauth_pkce_enabled": true
                  }
                }
              ]
            }
          }

  dataFrom:
    - extract:
        key: app-paperless

    - extract:
        key: app-paperless-kanidm-oidc
      rewrite:
        - regexp:
            source: "(.*)"
            target: kanidm_$1
