---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: paperless
spec:
  displayname: paperless
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/paperless-ngx.svg
  kanidmRef:
    name: kanidm
    namespace: security
  origin: https://paperless.hayden.moe/
  redirectUrl:
    - https://paperless.hayden.moe/accounts/oidc/kanidm/login/callback/
  scopeMap:
    - group: paperless_users
      scopes:
        - openid
        - profile
        - email
        - groups

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: paperless-users
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  kanidmName: paperless_users
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - hayden
    - invisible

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: paperless-admins
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  kanidmName: paperless_admins
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - hayden

---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: paperless-kanidm-oidc
spec:
  refreshInterval: 5m
  deletionPolicy: Delete
  updatePolicy: Replace
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: paperless-kanidm-oauth2-credentials
  data:
    - match:
        secretKey: CLIENT_ID
        remoteRef:
          remoteKey: app-paperless-kanidm-oidc
          property: key
    - match:
        secretKey: CLIENT_SECRET
        remoteRef:
          remoteKey: app-paperless-kanidm-oidc
          property: secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-kanidm-oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-kanidm-oidc
  data:
    - secretKey: key
      remoteRef:
        key: app-paperless-kanidm-oidc
        property: key
    - secretKey: secret
      remoteRef:
        key: app-paperless-kanidm-oidc
        property: secret
