---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: pihole/pihole
              tag: 2025.05.1
              pullPolicy: IfNotPresent
            env:
              TZ: "Europe/London"
              FTLCONF_dns_listeningMode: 'all'

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 8Gi
        globalMounts:
          - path: /etc/pihole

    route:
      main:
        hostnames:
          - "{{ .Release.Name }}.hayden.moe"
          - pihole.hayden.moe
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: 80

    service:
      main:
        type: LoadBalancer
        controller: main
        annotations:
          lbipam.cilium.io/ips: "192.168.2.12" # should be static
        ports:
          http:
            port: 80
            protocol: HTTP
          https:
            enabled: true
            port: 443
            protocol: HTTPS
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
