---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-anubis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ${APP}-anubis-key
  data:
    - secretKey: ED25519_PRIVATE_KEY_HEX
      remoteRef:
        key: svc-anubis
        property: private key
