---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-pg-barman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ai-pg-barman
    template:
      data:
        ACCESS_KEY_ID: "{{ .accessKeyId }}"
        SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
  dataFrom:
    - extract:
        key: strg-ucos-haydenmoe-volsync-postgres

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-honcho
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: db-honcho
    template:
      metadata:
        annotations:
          cnpg.io/reload: 'true'
      type: kubernetes.io/basic-auth
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
  dataFrom:
    - extract:
        key: db-honcho
