---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ai-pg
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie

  instances: 1

  storage:
    size: 5Gi
    storageClass: ceph-block

  backup:
    retentionPolicy: 7d

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: ai-pg-barman-os

  monitoring:
    enablePodMonitor: true

  postgresql:
    extensions:
    - name: pgvector
      image:
        # renovate: suite=trixie-pgdg depName=postgresql-18-pgvector
        reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie

  managed:
    roles:
      - name: honcho
        ensure: present
        comment: Honcho Memory
        login: true
        superuser: false
