---
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: shared-igpu
  namespace: default
spec:
  devices:
    requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.intel.com
