---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tactica-dev
spec:
  chartRef:
    kind: OCIRepository
    name: tactica
  interval: 30m
  values:
    tactica:
      appKey:
        existingSecret:
          name: tactica-dev-secret
          secretKey: appKey

      debug: true
      domain: dev.tactica.systems

      logging:
        level: debug

      db:
        host: tactica-dev-pg-rw
        existingSecret:
          name: tactica-dev-pg-app
          databaseKey: 'dbname'
          usernameKey: 'user'
          passwordKey: 'password'

      redis:
        host: tactica-dev-redis
        port: 6379

      mail:
        smtp:
          host: 'smtp-relay.selfhosted'
        from:
          address: tactica@hayden.moe
          name: Tactica (DEV!)

    defaultPodOptions:
      imagePullSecrets:
        - name: imp-forgejo

    controllers:
      main:
        containers:
          main:
            image:
              tag: latest@sha256:b9b1de296c95de84238b5c593fd2315660c659c87b2b71281ca5ef296bdc820a

    server:
      controllers:
        main:
          replicas: 1

    worker:
      controllers:
        main:
          replicas: 1
