---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argocd
spec:
  interval: 5m
  url: https://argoproj.github.io/argo-helm
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
spec:
  interval: 1h
  chart:
    spec:
      chart: argo-cd
      version: 8.5.4
      sourceRef:
        kind: HelmRepository
        name: argocd
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      domain: argocd.hayden.moe
    configs:
      params:
        server.insecure: true
