---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    template:
      data:
        WEBUI_SECRET_KEY: "{{ .secretKey }}"
        OAUTH_CLIENT_ID: "{{ .kanidm_clientId }}"
        OAUTH_CLIENT_SECRET: "{{ .kanidm_clientSecret }}"
  dataFrom:
    - extract:
        key: app-openwebui

    - extract:
        key: app-openwebui-kanidm-oidc
      rewrite:
        - regexp:
            source: "(.*)"
            target: "kanidm_$1"
