---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
spec:
  replicas: 2
  shards: 1

  keeperClusterRef:
    name: keeper

  dataVolumeClaimSpec:
    resources:
      requests:
        storage: 24Gi

  settings:
    extraUsersConfig:
      users: {}
      profiles:
        readwrite:
          readonly: 0
          max_memory_usage: 10000000000
        readonly:
          readonly: 1
          max_memory_usage: 10000000000
      quotas:
        default:
          interval:
            duration: 3600
            queries: 1000
            errors: 100

    tls:
      enabled: true
      required: false
      serverCertSecret:
        name: clickhouse-server-cert

---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: keeper
spec:
  replicas: 1
  dataVolumeClaimSpec:
    resources:
      requests:
        storage: 10Gi
