---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hayden-moe
spec:
  secretName: hayden-moe-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: hayden.moe
  dnsNames: ["hayden.moe", "*.hayden.moe"]
