---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname external.hayden.moe
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.2.22
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.hayden.moe,at.hayden.moe
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.hayden.moe"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.hayden.moe"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: hayden-moe-tls
    - name: https-atp
      protocol: HTTPS
      port: 443
      hostname: "*.at.hayden.moe"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: at-hayden-moe-tls
