---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: honcho
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: honcho-secret
    template:
      data:
        # DB
        DB_CONNECTION_URI: 'postgresql+psycopg://{{ .db_username }}:{{ .db_password }}@{{ .db_server }}:{{ .db_port }}/{{ .db_database }}'

        # OpenRouter
        LLM_OPENAI_BASE_URL: 'http://litellm.ai:4000'
        LLM_OPENAI_API_KEY: '{{ .litellmKey }}'
  dataFrom:
    - extract:
        key: app-honcho
    - extract:
        key: db-honcho
      rewrite:
        - regexp:
            source: "(.*)"
            target: db_$1
